function theta1=solve_chord(theta,x,y,R)
[x_cor,y_cor]=meshgrid(x,y);
x=x_cor';y=y_cor';
% y_s=[R*cos(theta),R*sin(theta)];
% x_y=[x,y];
% cos_phi=(R-x*cos(theta)-y*sin(theta))./sqrt((x-R*cos(theta)).^2+(y-R*sin(theta)).^2);
% sin_phi=sqrt(1-cos_phi.^2);
% theta1=atan((2*cos_phi.*sin_phi+cos(theta))./(2*cos_phi.^2+sin(theta)));
% cos_theta1=(2*x.*(R^2 - x.*R*cos(theta)- y.*R*sin(theta)))./(...
%  R*(R^2 + x.^2 + y.^2 - 2*x.*R*cos(theta) - 2*y.*R*sin(theta))) - (...
%  2*cos(theta).* (R^2 - x.*R*cos(theta) - y.*R*sin(theta)).* (1 - (...
%     R^2 + x.^2 + y.^2 - 2*x.*R*cos(theta) - 2*y.* R*sin(theta))./(...
%     2*(R^2 - x.*R*cos(theta) - y.*R*sin(theta)))))./(...
%  R^2 + x.^2 + y.^2 - 2*x.*R*cos(theta) - 2 *y.* R*sin(theta));

cos_theta1=(R*(-R^2 + x.^2 + y.^2).*cos(theta) - ...
 2*x.*(-R^2 + x.*R*cos(theta) + y.*R*sin(theta)))./(R*(R^2 + x.^2 + y.^2 - ...
   2*x.*R*cos(theta) - 2*y.*R*sin(theta)));

sin_theta1=(-2*y.*(-R^2 + x.*R*cos(theta) + y.*R*sin(theta)) + ...
 R.*(-R^2 + x.^2 + y.^2).*sin(theta))./(R*(R^2 + x.^2 + y.^2 - ...
   2*x.*R*cos(theta) - 2*y.*R*sin(theta)));
theta1=acos(cos_theta1);
theta1=real(theta1);
theta1(sin_theta1<0)=2*pi-theta1(sin_theta1<0);
theta1=mod(theta1,2*pi);

